CREATE TABLE Users(
id SERIAL PRIMARY KEY,
password VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
createdAt DATE DEFAULT CURRENT_DATE,
updatedAt DATE,
isadmin BOOLEAN DEFAULT FALSE);

CREATE TABLE profile(
id INTEGER,
last_name VARCHAR(255),
first_name VARCHAR(255),
age INTEGER,
gender CHAR,
city VARCHAR(255),
province VARCHAR(255),
country VARCHAR(255),
description VARCHAR(255),
FOREIGN KEY (id) REFERENCES Users ON DELETE CASCADE ON UPDATE CASCADE,
PRIMARY KEY(id));

CREATE TABLE topics(
topicid SERIAL PRIMARY KEY, 
description VARCHAR(255));

CREATE TABLE movie(
movieid SERIAL PRIMARY KEY, 
moviename VARCHAR(255) NOT NULL,
duration SMALLINT,
date_release VARCHAR(255),
language VARCHAR(255),
imageurl VARCHAR(255),
plot TEXT,
country VARCHAR(255),
awards VARCHAR(255));

CREATE TABLE watches(
id INTEGER, 
movieid INTEGER, 
watchdate DATE, 
rating SMALLINT,
FOREIGN KEY (id) REFERENCES users ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (movieid) REFERENCES movie ON DELETE CASCADE ON UPDATE CASCADE,
PRIMARY KEY (id, movieid));

CREATE TABLE movietopics(
topicid INTEGER, 
movieid INTEGER,
FOREIGN KEY (topicid) REFERENCES topics ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (movieid) REFERENCES movie ON DELETE CASCADE ON UPDATE CASCADE,
PRIMARY KEY(topicid, movieid));
