CREATE TABLE account(
userid SERIAL PRIMARY KEY,
password VARCHAR(255) NOT NULL,
last_name VARCHAR(255) NOT NULL,
first_name VARCHAR(255) NOT NULL,
join_date DATE DEFAULT CURRENT_DATE,
email VARCHAR(255) NOT NULL,
city VARCHAR(255),
province VARCHAR(255),
country VARCHAR(255),
isAdmin BOOLEAN DEFAULT FALSE);

CREATE TABLE profile(
userid INTEGER,
age INTEGER,
gender CHAR,
description VARCHAR(255),
FOREIGN KEY (userid) REFERENCES account ON DELETE CASCADE ON UPDATE CASCADE,
PRIMARY KEY(userid));

CREATE TABLE topics(
topicid SERIAL PRIMARY KEY, 
description VARCHAR(255));

CREATE TABLE movie(
movieid SERIAL PRIMARY KEY, 
moviename VARCHAR(255) NOT NULL,
duration SMALLINT,
date_release VARCHAR(255),
language VARCHAR(255),
imageurl VARCHAR(255),
plot TEXT,
country VARCHAR(255),
awards VARCHAR(255));

CREATE TABLE watches(
userid INTEGER, 
movieid INTEGER, 
watchdate DATE, 
rating SMALLINT,
FOREIGN KEY (userid) REFERENCES account ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (movieid) REFERENCES movie ON DELETE CASCADE ON UPDATE CASCADE,
PRIMARY KEY (userid, movieid));

CREATE TABLE movietopics(
topicid INTEGER, 
movieid INTEGER,
FOREIGN KEY (topicid) REFERENCES topics ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (movieid) REFERENCES movie ON DELETE CASCADE ON UPDATE CASCADE,
PRIMARY KEY(topicid, movieid));
