CREATE TABLE Actor(
    ActorID = SERIAL,
    lastname = VARCHAR(255) NOT NULL,
    firstname = VARCHAR(255) NOT NULL,
    DateOfBirth = DATE,
    country = VARCHAR(255),
    Bio = TEXT,
    PRIMARY KEY(ActorID));

CREATE TABLE Role(
    RoleID = SERIAL,
    name = VARCHAR(255) NOT NULL,
    ActorID = INTEGER,
    PRIMARY KEY(RoleID),
    FOREIGN KEY(ActorID) REFERENCE Actor ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE ActorPlays(
    MovieID = INTEGER,
    ActorID = INTEGER,
    FOREIGN KEY(MovieID) REFERENCE movie ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(ActorID) REFERENCE Actor ON DELETE CASCADE ON UPDATE CASCADE, 
    PRIMARY KEY(MovieID, ActorID));

CREATE TABLE Director(
    DirectorID = SERIAL,
    lastname = VARCHAR(255) NOT NULL,
    firstame = VARCHAR(255) NOT NULL,
    DateOfBirth = DATE,
    country = VARCHAR(255),
    PRIMARY KEY(DirectorID));

CREATE TABLE Directs(
    DirectorID = INTEGER,
    MovieID = INTEGER,
    FOREIGN KEY(DirectorID) REFERENCE Director ON UPDATE CASCADE ON DELETE CASCADE, 
    FOREIGN KEY(MovieID) REFERENCE movie ON UPDATE CASCADE ON DELETE CASCADE
    PRIMARY KEY(directorid, movieid);

CREATE TABLE Studio(
    StudioID = SERIAL,
    name = VARCHAR(255) NOT NULL,
    country = VARCHAR(255),
    PRIMARY KEY(StudioID));

CREATE TABLE Sponsors(
    StudioID = INTEGER,
    MovieID = INTEGER,
    FOREIGN KEY(StudioID) REFERENCE Studio ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(MovieID) REFERENCE Movie, ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY(studioid, movieid));
